# server
server:
  port: 8081

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://43.142.170.129:3306/test?useUnicode=true&amp&useSSL=false&amp&characterEncoding=UTF-8&amp&serverTimezone=GMT%2B8
    driver-class-name:  com.mysql.jdbc.Driver
    username: root
    password: chenyu@123!

# mybatis-plus 开启日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

