spring:
  # 数据源
  datasource:
    url: jdbc:mysql://121.36.66.131:3306/test?useUnicode=true&amp&useSSL=false&amp&characterEncoding=UTF-8&amp&serverTimezone=GMT%2B8
    driver-class-name:  com.mysql.jdbc.Driver
    username: root
    password: password
    #    url: jdbc:mysql://localhost:3306/test?useUnicode=true&amp&useSSL=false&amp&characterEncoding=UTF-8&amp&serverTimezone=GMT%2B8
    #    driver-class-name:  com.mysql.jdbc.Driver
    #    username: root
    #    password: password
    # jpa
    jpa:
      hibernate:
        ddl-auto: update  # 建表策略
      show-sql: true  #显示SQL语句

  # redis
  redis:
    host: 121.36.66.131
    #    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 10000
